# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    container: python:3.9 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install setuptools wheel twine
    - name: Get tag
      uses: dawidd6/action-get-tag@v1.0.0
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        CI_COMMIT_TAG: ${{ steps.tag.outputs.tag }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
