name: Robot tests

on: [push, pull_request]

jobs:
  integrationtest:
    runs-on: ubuntu-latest
    container: python:3.10
    strategy:
      fail-fast: false
      matrix:
        auth_enabled: ['false', 'true']      
        camunda_version: ['run-7.24.0']
    services:
      camunda:
        image: camunda/camunda-bpm-platform:${{ matrix.camunda_version }}
        ports:
          - 8080:8080
        env:
          camunda.bpm.run.auth.enabled: ${{ matrix.auth_enabled }}
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        activate-environment: true
    - name: Test with robot
      run: |
        uv sync --group ci
        sleep 10
        robotcode -p ci robot tests/robot/**/*.robot
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: robot logs-${{matrix.camunda_version}}-${{matrix.auth_enabled}}
        path: |
          results
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
          name: robot logs-${{matrix.camunda_version}}-${{matrix.auth_enabled}}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: xunit.xml
